---
- name: Download BGInfo
  win_get_url:
    url: '{{ bginfo_download_url }}'
    dest: C:\Windows\Temp\BGInfo.zip
    force: no

- name: Unzip BGInfo
  win_unzip:
    src: 'C:\Windows\Temp\BGInfo.zip'
    dest: '%SystemDrive%\BGInfo'

- name: Copy logon.bgi
  win_copy:
    src: 'templates/logon.bgi'
    dest: '%SystemDrive%\BGInfo\logon.bgi'

- name: Autostart BGInfo
  win_shortcut:
    src: '%SystemDrive%\BGInfo\BGInfo.exe'
    dest: '%ProgramData%\Microsoft\Windows\Start Menu\Programs\StartUp\BGInfo.lnk'
    arguments: '%SystemDrive%\BGInfo\logon.bgi /timer:0 /nolicprompt'